ALTER SESSION SET CONTAINER=FREEPDB1;

CREATE USER QDev IDENTIFIED BY Test123 QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO QDev;

GRANT SELECT on V_$DATABASE to QDev;
GRANT SELECT on V_$THREAD to QDev;
GRANT SELECT on V_$PARAMETER to QDev;
GRANT SELECT on V_$NLS_PARAMETERS to QDev;
GRANT SELECT on V_$TIMEZONE_NAMES to QDev;
GRANT SELECT on ALL_INDEXES to QDev;
GRANT SELECT on ALL_OBJECTS to QDev;
GRANT SELECT on ALL_TABLES to QDev;
GRANT SELECT on ALL_USERS to QDev;
GRANT SELECT on ALL_CATALOG to QDev;
GRANT SELECT on ALL_CONSTRAINTS to QDev;
GRANT SELECT on ALL_CONS_COLUMNS to QDev;
GRANT SELECT on ALL_TAB_COLS to QDev;
GRANT SELECT on ALL_IND_COLUMNS to QDev;
GRANT SELECT on ALL_LOG_GROUPS to QDev;
GRANT SELECT on SYS.DBA_REGISTRY to QDev;
GRANT SELECT on SYS.OBJ$ to QDev;
GRANT SELECT on DBA_TABLESPACES to QDev;
GRANT SELECT on ALL_TAB_PARTITIONS to QDev;
GRANT SELECT on ALL_ENCRYPTED_COLUMNS to QDev;
GRANT SELECT ANY TRANSACTION to QDev;
GRANT SELECT on V_$LOGMNR_LOGS to QDev;
GRANT SELECT on V_$LOGMNR_CONTENTS to QDev;
GRANT SELECT on V_$LOG to QDev;
GRANT SELECT on V_$ARCHIVED_LOG to QDev;
GRANT SELECT on V_$LOGFILE to QDev;
GRANT SELECT on V_$TRANSACTION to QDev;
GRANT SELECT on ALL_VIEWS to QDev;
